---
title: "Age and meaning"
author: "Lukáš Hejtmánek"
date: "5 5 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
source(here("functions/questions.R"))
source(here("functions/process.R"))
source(here("functions/loading.R"))
library(GGally)
library(psych)
library(correlation)
```

```{r}
df_question_categories <- read.table(here("data/processed/question-categories.csv"),
                                     sep=";", header=TRUE)
df_processed <- load_processed() %>%
  filter(!is.na(ended),
         vek > 35) %>%
  filter(language == "czech")
```


```{r}
df_processed %>%
  ggplot(aes(vek, mlq_s_search)) + geom_point() +
    geom_smooth(method="lm")
```

```{r}
df_processed %>%
  filter(pohl != "O") %>%
  ggplot(aes(vek, mlq_s_search, color=pohl)) + 
    geom_point() +
    geom_smooth(method="lm")
```

```{r}
glm_mlqsearch_pohl_vek <- glm(mlq_s_search ~ vek * pohl, 
                               data = filter(df_processed, pohl != "O"))
summary(glm_mlqsearch_pohl_vek)
```

```{r}
df_processed %>%
  filter(vzdel != "elementary") %>%
  ggplot(aes(vek, mlq_s_search, color=vzdel)) + 
    geom_point() +
    geom_smooth(method="lm")
```

```{r}
glm_mlqsearch_vzdel_vek <- glm(mlq_s_search ~ vek * vzdel, 
                               data = filter(df_processed, vzdel != "elementary"))
summary(glm_mlqsearch_vzdel_vek)
```