---
title: "Demographics reports"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(scales)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
source(here("functions/questions.R"))
source(here("functions/process.R"))
source(here("functions/loading.R"))
load_questions()
library(plotly)

COLORS <- c("#2a3e4e","#22323e", "#2a587c", "#416b8b","#cdd0df", "#ffffff")
TXT_COLORS <- c("#ffffff","#ffffff", "#ffffff", "#ffffff", "#000000", "#000000")
BG_COLOR <- "#dfe8f1"
```

```{r}
df_processed <- load_processed()
df_processed <- df_processed %>%
  filter(language=="czech",
         !is.na(ended) | source == "paper",
         vek > 40)
```

## Demografie
```{r demo functions, echo=FALSE}
plt_histogram <- function(df_data, variable, binsize, title){
  plt <- df_data %>%
    plot_ly(., x=enquo(variable), type="histogram", histnorm="probability",
            xbins=list(size=binsize), colors = COLORS[2]) %>%
    layout(title = list(text = title, font = list(size=24), x = 0.05),
            xaxis = list(title = "",
                        showgrid = FALSE,
                        showline = FALSE,
                        zeroline = FALSE),
           yaxis = list(title = "",
                        showgrid = FALSE,
                        showline = FALSE,
                        tickformat = "1%",
                        zeroline = FALSE),
           barmode = 'stack',
           paper_bgcolor = BG_COLOR, plot_bgcolor = BG_COLOR,
           margin = list(t=50),
         showlegend = FALSE)
  return(plt)
}

plt_pie_chart <- function(df_data, variable, title){
  fig <- df_data %>%
    select(group = .data[[variable]]) %>%
    filter(!is.na(group)) %>%
    count(group) %>%
    mutate(ratio = n/sum(n),
           percent = percent(n/sum(n), accuracy=0.01)) %>%
    plot_ly(., labels = ~group , values = ~n, type = 'pie',
            textposition = 'inside',
            textinfo = 'label+percent',
            marker=list(colors=COLORS)) %>%
    layout(title = list(text = title , yanchor="auto", xanchor="center", x = 0.3, y = 1.1),
           paper_bgcolor = BG_COLOR, plot_bgcolor = BG_COLOR,
           margin = list(t=50),
           showlegend = FALSE)
  return(fig)
}

# Requires column name and column N
plt_bar_ratio <- function(df_data, title){
  plt <- df_data %>%
    mutate(ratio = n/sum(n)) %>%
    plot_ly(., x = ~name, y = ~ratio, color = ~name, 
          type = 'bar', colors = COLORS) %>%
  layout(
    title = list(text=title, x = 0.1),
    showlegend = FALSE,
    yaxis=list(tickformat="1%",
                    title=""),
         xaxis=list(title=""),
         barmode = 'stack',
         paper_bgcolor = BG_COLOR, plot_bgcolor = BG_COLOR,
         margin = list(t=50)
         )
  return(plt)
}

create_stacked_bar <- function(df_data, selected_vars, width = 600, height = 200,
                               title = ""){
  data <- df_data %>%
    select(selected_vars) %>%
    pivot_longer(everything()) %>%
    filter(!is.na(value)) %>%
    count(name, value) %>%
    group_by(name) %>%
    mutate(name = get_question_text(name),
           ratio = n/sum(n),
           percent = round(ratio*100, 2),
           name = sapply(name, function(x){
             paste(strwrap(x, width = 54),collapse = "<br>")
            }, USE.NAMES = FALSE),
           name = unname(name)) %>%
    select(y = name, value, percent) %>%
    pivot_wider(names_from = value, names_prefix = "x", values_from = percent) %>%
    as.data.frame()
  
  top_labels <- get_question_labels(selected_vars[1])
  
  answer_options <- str_c("x", seq_len(sum(grepl("x", colnames(data)))))
  
  fig <- plot_ly(data, x = ~x1, y = ~y, type = 'bar', orientation = 'h', 
                 hovertemplate = str_glue("{top_labels[1]}, {data$x1} %"),
                 marker = list(color = COLORS[1], line = list(color = 'rgb(248, 248, 249)', width = 1)),
                 width = width, height = height)
  for(i in seq(2, length(answer_options))){
    answer_option <- answer_options[i]
    fig <- fig %>% add_trace(x = data[[answer_option]],
                             hovertemplate = str_glue("{top_labels[i]}, {data[[answer_option]]} %"),
                             marker = list(color = COLORS[i]))
  }
  
  fig <- fig %>% layout(
          title=list(text=title, x=0.1),
          xaxis = list(title = "",
                        showgrid = FALSE,
                        showline = FALSE,
                        showticklabels = FALSE,
                        zeroline = FALSE,
                        domain = c(0.1, 1)),
           yaxis = list(title = "",
                        showgrid = FALSE,
                        showline = FALSE,
                        showticklabels = FALSE,
                        zeroline = FALSE),
           barmode = 'stack',
           paper_bgcolor = BG_COLOR, plot_bgcolor = BG_COLOR,
           margin = list(l = 250, r = 10, t = 140, b = 80),
           showlegend = FALSE) 
  
  # labeling the y-axis ----
  fig <- fig %>% add_annotations(xref = 'paper', yref = 'y', x = 0.1, y = data$y,
                    xanchor = 'right', text = data$y,
                    font = list(family = 'Arial', size = 12,
                              color = 'rgb(67, 67, 67)'),
                    showarrow = FALSE, align = 'right')
  
  # labeling the percentages of each bar (x_axis) ----
  plt <- fig
  for(i in 1:length(answer_options)){
    var_name <- answer_options[i]
    if(i == 1){
      position <- data[, var_name]/2
    } else {
      if(i == 2){
        position <- data[, answer_options[1:(i-1)]] + data[, var_name]/2
      } else {
        position <- rowSums(data[, answer_options[1:(i-1)]]) + data[, var_name]/2
      }
    }
    txt_percent <- str_glue("{top_labels[i]}<br>{data[,var_name]} %")
    txt_percent[data[,var_name] < 10] <- str_glue("{data[,var_name][data[,var_name] < 10]} %")
    txt_percent[data[,var_name] < 5] <- ""
    txt_percent[is.na(data[,var_name])] <- ""
    
    plt <- plt %>% add_annotations(xref = 'x', yref = 'y',
                    x = position, y = data$y,
                    text = txt_percent,
                    font = list(family = 'Arial', size = 12,
                              color = TXT_COLORS[i]),
                    showarrow = FALSE)
  }
  
    # labeling the first Likert scale (on the top)
  plt <- plt %>% add_annotations(xref = 'x', yref = 'paper',
                    x = c(5, 95),
                    y = 1.15,
                    text = top_labels[c(1,6)],
                    font = list(family = 'Arial', size = 12,
                                color = 'rgb(67, 67, 67)'),
                    showarrow = FALSE)
  return(plt)
}
```

```{r plot vek}
plt_histogram(df_processed, vek, 5, "Distribuce věkových skupin")
```

?? remove Other? Only `r nrow(filter(df_processed, pohl=="O"))` observations.
```{r plot gender}
df_processed %>%
  filter(pohl != "O") %>%
  mutate(gender = recode(pohl, "M" = "muž", "F" = "žena")) %>%
  plt_pie_chart("gender", "Pohlaví")
```

```{r demo vzdelani}
df_processed %>%
  filter(!is.na(vzdel)) %>%
  mutate(vzdel = recode(vzdel, "elementary" = "základní škola", "high school" = "Střední škola", "university" = "Vysoká škola")) %>%
  plt_pie_chart("vzdel", "Vzdělání")

df_processed %>%
  group_by(vzdel) %>%
  summarise(absolute = n(),
            relative = label_percent(accuracy=0.1)(n()/nrow(df_processed))) %>%
  knitr::kable()
```

```{r }
df_processed %>%
  filter(!is.na(zamest)) %>%
  summarise("Má stálé zaměstnání" = grepl("1", zamest),
            "Podníká, OSVČ" = grepl("2", zamest),
            "Nemá stálou práci" = grepl("3", zamest),
            "Na mateřské, v důchodu" = grepl("4", zamest)
            ) %>%
  pivot_longer(everything()) %>%
  filter(value) %>%
  plt_pie_chart("name", "Povolání")
```

```{r bydleni}
## POkoje
df_processed %>%
  select(byd_pok) %>%
  filter(!is.na(byd_pok)) %>%
  mutate(byd_pok = as.numeric(byd_pok),
         byd_cut = cut(byd_pok, breaks=c(seq(0,6), 20),
                        labels = c(seq(1,6), "7+"))) %>%
  count(byd_cut) %>%
  select(name = byd_cut, n) %>%
  plt_bar_ratio("Počet pokojů (bez koupelny a kuchyně)")
```

```{r deti}
df_processed %>%
  select(deti_poc) %>%
  filter(!is.na(deti_poc),
         deti_poc > 0) %>%
  mutate(deti_poc = cut(deti_poc, breaks=c(seq(0,4), 20),
                        labels = c(seq(1,4), "5+"))) %>%
  count(deti_poc) %>%
  select(name = deti_poc, n) %>%
  plt_bar_ratio("Počet dětí")
```
```{r marital status}
df_processed %>%
  select(starts_with("family_"),
         -family_s_total) %>%
  pivot_longer(everything()) %>%
  count(name, value) %>%
  group_by(name) %>%
  mutate(ratio = n/sum(n),
         value = factor(value, c(1,0), labels = c("Ano", "Ne")),
         name = recode(name, "family_divorced" = "Rozvedený/á",
                       "family_married" = "Ženatý/á",
                       "family_relationship" = "Dlouhodobý vztah",
                       "family_single" = "Svobodný/á",
                       "family_widowed" = "Ovdovělý/á")) %>%
  ungroup() %>%
  plot_ly(., x = ~name, y = ~ratio, color = ~value, 
          type = 'bar', colors = COLORS[c(1, 3)]) %>%
  layout(title = list(text="Rodinný stav", x = 0.1),
    yaxis=list(tickformat="1%",
                    title=""),
         xaxis=list(title=""),
         barmode = 'stack',
         paper_bgcolor = BG_COLOR, plot_bgcolor = BG_COLOR,
          margin = list(t=50)
         )
# Add pie chart
df_processed %>%
  select(starts_with("family_"),
         -family_s_total) %>%
  pivot_longer(everything()) %>%
  mutate(value = factor(value, c(1,0), labels = c("Ano", "Ne")),
         name = recode(name, "family_divorced" = "Rozvedený/á",
                       "family_married" = "Ženatý/á",
                       "family_relationship" = "Dlouhodobý vztah",
                       "family_single" = "Svobodný/á",
                       "family_widowed" = "Ovdovělý/á")) %>%
  filter(value == "Ano") %>%
  plt_pie_chart("name", "Rodiný stav")
```
## Hodinová dedikace
```{r}
df_time_dedication <- df_processed %>%
  select(da1, da2, da3, da4) %>%
  mutate(time_sum = da1 + da2 + da3 + da4,
         week_ratio = time_sum/(24*7)) %>%
  mutate(across(starts_with("da"), ~.x/time_sum, .names="{.col}_ratio")) %>%
  mutate(across(matches("da\\d$"), ~cut(.x, c(seq(0,60,5), 1000),
                                        labels=c(seq(5,60,5), "61+")),
                .names="{.col}_cut"))

df_time_dedication %>%
  plot_ly(data=., x=~week_ratio, type="histogram", histnorm="probability")

df_time_dedication %>%
  select(matches("da\\d_ratio")) %>%
  pivot_longer(everything()) %>%
  filter(!is.na(value)) %>%
  ggplot(aes(value)) +
    geom_histogram() +
    facet_wrap(~name)

df_time_dedication %>%
  count(da1_cut) %>%
  select(name = da1_cut, n) %>%
  plt_bar_ratio("Počet hodin týdně v práci nebo prací za finanční odměnu")

df_time_dedication %>%
  count(da2_cut) %>%
  select(name = da2_cut, n) %>%
  plt_bar_ratio("Počet hodin týdně věnovaný péči o druhé (děti, rodiče, příbuzné)")

df_time_dedication %>%
  count(da3_cut) %>%
  select(name = da3_cut, n) %>%
  plt_bar_ratio("Počet hodin týdně věnovaný péči o majetek a domácnost")

df_time_dedication %>%
  count(da4_cut) %>%
  select(name = da4_cut, n) %>%
  plt_bar_ratio("Počet hodin týdně věnovaný péči o sebe a své záliby")
```
## Finanční situace
```{r}
questionnaire_plot <- function(data, question){
  max_val <- ceiling(max(table(df_processed[[question]])/nrow(df_processed))*10)/10
  plt <- ggplot(df_processed, aes_string(x = question)) +
    geom_bar(aes(y = after_stat(count/sum(count)))) +
    scale_y_continuous(labels = percent, limits = c(0, max_val)) +
    coord_flip() +
    labs(y = str_wrap(get_question_text(question), 80),
         x = "") +
    scale_x_continuous(breaks = c(1, get_question_max_value(question)),
                       labels = c(get_question_labels(question)[c(1, get_question_max_value(question))])) +
    geom_text(aes(x = .data[[question]], y = after_stat(count / sum(count)),
                  label = label_percent(accuracy = 1)(after_stat(count / sum(count)))),
              stat="count", hjust =-0.1, color = grey(0.2))
  return(plt)
}

questionnaire_plot <- function(data, question){
  max_val <- ceiling(max(table(df_processed[[question]])/nrow(df_processed))*10)/10
  plt <- ggplot(df_processed, aes_string(x = question)) +
    geom_bar(aes(y = after_stat(count/sum(count)))) +
    scale_y_continuous(labels = percent, limits = c(0, max_val)) +
    coord_flip() +
    labs(y = str_wrap(get_question_text(question), 80),
         x = "") +
    scale_x_continuous(breaks = c(1, get_question_max_value(question)),
                       labels = c(get_question_labels(question)[c(1, get_question_max_value(question))])) +
    geom_text(aes(x = .data[[question]], y = after_stat(count / sum(count)),
                  label = label_percent(accuracy = 1)(after_stat(count / sum(count)))),
              stat="count", hjust =-0.1, color = grey(0.2))
  return(plt)
}

```

```{r}
create_stacked_bar(df_processed, "z1", 1200, 300, "Zhodnocení zdravotního stavu")
create_stacked_bar(df_processed, c("z2", "z3", "z4"), 1200, 400, "Frekvence zdravotních komplikací")
create_stacked_bar(df_processed, "z5", 1200, 300, "Zdravotní srovnání")
```


```{r finances}
create_stacked_bar(df_processed, c("e1", "e2"), 1200, 400, "Ekonomická situace")
```

## Opora v partnerství
```{r}
create_stacked_bar(df_processed, str_c("p", seq_len(6)), 1200, 500, "Frekvence partnerské opory")
create_stacked_bar(df_processed, str_c("p", seq(7, 12)), 1200, 500, "Frekvence partnerských konfliktů")
```
## Opora v rodině
```{r}
create_stacked_bar(df_processed, str_c("f", seq(1, 4)), 1200, 400, "Rodinná opora")
create_stacked_bar(df_processed, str_c("f", seq(5, 8)), 1200, 400, "Rodinné stresory")
```
## Opora v přátelích
```{r}
create_stacked_bar(df_processed, str_c("fs", seq(1, 4)), 1200, 400, "Opora v přátelích")
create_stacked_bar(df_processed, str_c("fs", seq(6, 8)), 1200, 400, "Přátelské stressory")
```
## Práce
```{r}
create_stacked_bar(df_processed, str_c("cs", seq(1, 3)), 1200, 400, "Pracovní zátěž")
create_stacked_bar(df_processed, str_c("cs", seq(4, 5)), 1200, 400, "Pracovně emoční zátěž")
create_stacked_bar(df_processed, str_c("cs", seq(6, 8)), 1200, 400, "Pracovní smysluplnost")
create_stacked_bar(df_processed, str_c("cs", seq(9, 10)), 1200, 400, "Pracovní spokojenot")
create_stacked_bar(df_processed, str_c("cs", seq(11, 16)), 1200, 600, "Práce a osobní život")
```
## Volný čas a aktivity
```{r}
cinnost_plot <- function(df_data, cinnost){
  fig <- df_data %>%
    filter(!is.na(df_data[[cinnost]])) %>%
    mutate(val = ifelse(.[[cinnost]] == 1, "ano", "ne")) %>%
    count(val) %>%
    mutate(prop = n / sum(n),
           ypos = cumsum(prop)- 0.5*prop,
           lab = paste0(val,"\n(",label_percent(accuracy = 1)(prop), ")")) %>%
    plot_ly(., labels = ~val, values = ~n, type = 'pie',
            textposition = 'inside',
            textinfo = 'label+percent',
            marker = list(colors = COLORS)) %>% 
    layout(title = list(text = ~get_question_text(cinnost), 
                      yanchor="top", xanchor="center",
                      x = 0.3, y = 1),
         showlegend = FALSE)
  return(fig)
}

plt_percent_bar <- function(df_data, values, codes, title){
  df_question <- df_data %>%
    select(ident, values) %>%
    rename_with(~codes, .cols = values) %>%
    pivot_longer(-ident) %>%
    group_by(name) %>%
    count(happened = value > 0) %>%
    filter(!is.na(happened)) %>%
    pivot_wider(names_from = happened, values_from = n) %>%
    mutate(ratio = `TRUE`/sum(`TRUE`, `FALSE`)) %>%
    arrange(ratio) %>%
    mutate(percent = percent(ratio, accuracy = 0.01, decimal.mark = ","),
           name = get_question_text(name))
  
  fig <- plot_ly(df_question, x = ~ratio, y = ~reorder(name, ratio), name = "",
                 type = "bar", orientation = "h", width = 0.5,
          marker = list(color = COLORS[1],
                        line = list(color = 'rgb(248, 248, 249)', width = 1))) %>%
    add_trace(x = ~(1-ratio), marker = list(color = COLORS[4])) %>%
    layout(
          title = list(text=title, x = 0.05),
          xaxis = list(title = "",
                        showgrid = FALSE,
                        showline = FALSE,
                        tickformat = "1%",
                        zeroline = FALSE,
                        domain = c(0.15, 1)),
           yaxis = list(title = "",
                        showgrid = FALSE,
                        showline = FALSE,
                        zeroline = FALSE),
           barmode = 'stack',
           paper_bgcolor = BG_COLOR, plot_bgcolor = BG_COLOR,
           margin = list(l = 250, r = 10, t = 50, b = 20),
           showlegend = FALSE)
    
  return(list(table = df_question, plot = fig))
}
```

```{r}
cin_codes <- colnames(df_processed)[grep("cin\\d+$", colnames(df_processed))]

res <- plt_percent_bar(df_processed, values = cin_codes, codes = cin_codes,
                       "Volnočasová aktivita")

res$table %>%
  select("Volnočasová aktivita" = name, "Účast" = percent) %>%
  knitr::kable()

res$plot
```


## LCIS

```{r}
lcis_codes <- colnames(df_processed)[grep("lcis\\d+$", colnames(df_processed))]
lcis_vals <- str_c(lcis_codes, "_s_computedkol")

res <- plt_percent_bar(df_processed, values = lcis_vals, codes = lcis_codes,
                       "Významná životní událost")

res$table %>%
  select("Otázka" = name, "Procento lidí, kteří odpověděli ano" = percent) %>%
  knitr::kable()
```

```{r, fig.height=10}
res$plot %>% 
  layout(height = 900, width= 700, autosize=FALSE)
```

## Panas

```{r}
plt_histogram(df_processed, panas_s_hedonic, 0.5, "Distribuce emoční nálady") %>%
  layout(shapes = list(type='line', x0= 0, x1= 0, y0=0, y1=0.3))
```

## Swls

```{r}
df_processed %>%
  mutate(spokojenost = cut(.$swls_s_satifaction, breaks = c(0,3.1,4.9,7),
                          labels = c("Nespokojený", "Něco mezi", "Spokojený"))) %>%
  filter(!is.na(spokojenost)) %>%
  count(spokojenost) %>%
  mutate(ratio = n/sum(n),
         percent = percent(n/sum(n), accuracy=0.01)) %>%
  plot_ly(., labels = ~spokojenost, values = ~n, type = 'pie',
          textposition = 'inside',
          textinfo = 'label+percent',
          marker=list(colors=COLORS)) %>%
  layout(title = list(text = "Aktuální spokojenost se životem" , yanchor="auto", xanchor="center", x = 0.4, y = 1.1),
         showlegend = FALSE)
```

