---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(psych)
source(here("functions/questions.R"))
source(here("functions/process.R"))
source(here("functions/loading.R"))
source(here("reports/functions/loading.R"))
library(correlation)
```

```{r loading}
df_question_categories <- read.table(here("data/processed/question-categories.csv"),
                                     sep=";", header=TRUE)
df_processed <- load_report_data(language="czech")

# Takes ls column in a pivoted table
create_df_ls <- function(df_processed){
  df_ls <- df_processed %>%
    filter(!is.na(ident)) %>%
    select(ident, starts_with("LS"), vek) %>%
    pivot_longer(-c(ident, vek)) %>%
    mutate(name = str_replace(name, "ls85", "ls85_99"),
           name = str_remove(name, "ls")) %>%
    separate(name, c("ls_min", "ls_max"), "_", convert = TRUE, remove = FALSE) %>%
    mutate(ls_dist = (vek - ls_max),
           ls_state = cut(ls_dist, c(-Inf, -4, 4, Inf),
                          labels = c("future", "present", "past")))
  return(df_ls)
}
```

```{r}
df_ls <- df_processed %>%
  filter(!is.na(ident)) %>%
  select(ident, starts_with("LS"), vek)

df_ls_enhanced <- create_df_ls(df_processed)
```

```{r}
df_ls_enhanced %>%
  ggplot(aes(name, value)) +
    geom_boxplot() 
```

```{r}
df_ls_enhanced %>%
  ggplot(aes(vek, value)) +
    geom_point() + geom_smooth() + facet_wrap(~name)
```

```{r}
df_ls_enhanced %>%
  ggplot(aes(ls_state, value)) +
    geom_boxplot() +
    geom_jitter(width = 0.1)
```

```{r}
df_ls_enhanced %>%
  filter(ls_state == "past") %>%
  ggplot(aes(as.factor(ls_max), value)) +
    geom_boxplot()
    geom_jitter(width = 0.1)
```

```{r}
df_processed %>%
  filter(!is.na(ident), vzdel != "elementary") %>%
  select(ident, vzdel, starts_with("LS")) %>%
  pivot_longer(-c(ident, vzdel)) %>%
  ggplot(aes(name, value, fill=vzdel, color=vzdel)) + geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.1)
```

```{r}
df_processed %>%
  filter(!is.na(ident), pohl != "O") %>%
  select(ident, pohl, starts_with("LS")) %>%
  pivot_longer(-c(ident, pohl)) %>%
  ggplot(aes(name, value, fill=pohl, color=pohl)) + geom_boxplot() +
    geom_jitter(width = 0.2, alpha = 0.1)
```

```{r}
df_processed %>%
  select(ident, vek, starts_with("LS")) %>%
  pivot_longer(-c(ident, vek)) %>%
  mutate(a = str_match(name, "ls(\\d+)_(\\d+)")[2]) %>%
  head()

str_match(c("ls0_12", "ls5_12"), "ls(\\d+)_(\\d+)")[3]
```

