---
title: "dids-report"
author: "Lukáš Hejtmánek"
date: "5 5 2022"
output: html_document
---

```{r}
library(here)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
source(here("functions/questions.R"))
source(here("functions/process.R"))
source(here("functions/loading.R"))
library(GGally)
library(psych)
library(correlation)
```
```{r loading}
df_question_categories <- read.table(here("data/processed/question-categories.csv"),
                                     sep=";", header=TRUE)
df_processed <- load_processed() %>%
  filter(!is.na(ended))


df_processed <- filter(df_processed, language == "czech")
```

```{r factor analysis}
df_dids_items <- select(df_processed, get_question_codes("dids", df_processed))
ggcorr(df_dids_items, method = c("everything", "pearson")) 
```

```{r}
KMO(df_dids_items)
eigen(cor(df_dids_items, use = "complete.obs"))
scree(df_dids_items, pc=FALSE)
fa.parallel(df_dids_items, fa="fa")
```


```{r}
fit <- factanal(df_dids_items[complete.cases(df_dids_items),], 4, rotation="promax")
fit <- fa(df_dids_items, nfactors=4, rotate="varimax")
print(fit, digits=2, cutoff=0.3, sort=TRUE)
```
dids_s_commitment_making = dids_01 + dids_02 + dids_03 + dids_04 + dids_05
dids_s_exploration_breadth = dids_06 + dids_07 + dids_08 + dids_09 + dids_10
dids_s_ruminative_exploration = dids_11 + dids_12 + dids_13 + dids_14 + dids_15
dids_s_identification_with_commitment = dids_16 + dids_17 + dids_18 + dids_19 + dids_20
dids_s_exploration_depth = dids_21 + dids_22 + dids_23 + dids_24 + dids_25

```{r diagram ,fig.height=8, fig.width=6}
loads <- fit$loadings
fa.diagram(loads)
```