---
title: "goals-report"
author: "Lukáš Hejtmánek"
date: "5 5 2022"
output: html_document
---
```{r}
library(here)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
source(here("functions/questions.R"))
source(here("functions/process.R"))
source(here("functions/loading.R"))
library(GGally)
library(psych)
library(correlation)
```

```{r loading}
df_question_categories <- read.table(here("data/processed/question-categories.csv"),
                                     sep=";", header=TRUE)
df_processed <- load_processed() %>%
  filter(!is.na(ended))

df_processed <- filter(df_processed, language == "czech")
```

```{r factor analysis}
df_goals_items <- select(df_processed, 
                         get_question_codes("goal", df_processed))
df_goals_summaries <- select(df_processed, starts_with("goals_s_"), 
                             pohl, vek, vzdel, ident)
```

```{r}
df_goals_summaries %>%
  pivot_longer(-c(pohl, vek, vzdel, ident)) %>%
  filter(pohl != "O") %>%
  ggplot(aes(name, value, fill = pohl)) +
    geom_boxplot() +
    coord_flip()
```
