---
title: "Goals and SWLS"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(GGally)
library(psych)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
source(here("functions/questions.R"))
source(here("functions/process.R"))
source(here("functions/loading.R"))
```

```{r loading}
df_question_categories <- read.table(here("data/processed/question-categories.csv"),
                                     sep=";", header=TRUE)
df_processed <- load_processed() %>%
  filter(!is.na(ended)) %>%
  filter(language == "czech")
```

```{r}
df_mlq_items <- select(df_processed, get_question_codes("mlq", df_processed))
```

```{r factor analysis}
ggcorr(df_mlq_items, method = c("everything", "pearson")) 
```

```{r}
KMO(df_mlq_items)
eigen(cor(df_mlq_items, use = "complete.obs"))
scree(df_mlq_items, pc=FALSE)
fa.parallel(df_mlq_items, fa="fa")
```


```{r}
fit <- factanal(df_mlq_items[complete.cases(df_mlq_items),], 2, rotation="promax")
fit <- fa(df_mlq_items, nfactors=2, rotate="varimax")
print(fit, digits=2, cutoff=0.3, sort=TRUE)
```

mlq_s_presence = mlq_01 + mlq_04 + mlq_05 + mlq_06 + reversed(mlq_09, 7)
mlq_s_search = mlq_02 + mlq_03 + mlq_07 + mlq_08 + mlq_10

```{r diagram ,fig.height=8, fig.width=6}
loads <- fit$loadings
fa.diagram(loads)
```
